spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: http://localhost:9001
          predicates:
            # 匹配路径转发
            - Path=/system/**
server:
  port: 9002
eureka:
  client:
    service-url.DefaultZone: http://localhost:8761/eureka/
